version: '3.3'

networks:
  monitoring:
    driver: bridge
    
services:
  prometheus:
    build: prometheus
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring
  grafana:
    build: grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "3000:3000"