version: '3.3'

networks:
  monitoring:
    driver: bridge
    
services:
  prometheus:
    image: prom/prometheus
    working_dir: /etc/prometheus
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    working_dir: /etc/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "3000:3000"