version: '3.3'

networks:
  monitoring:
    driver: bridge
    
services:
  prometheus:
    build:
      context: prometheus
      dockerfile: DockerProm
    container_name: prometheus
    restart: always
    networks:
      - monitoring
  grafana:
    build:
      context: grafana
      dockerfile: DockerGraf
    container_name: grafana
    restart: always
    networks:
      - monitoring
    ports:
      - "3000:3000"