# Grafana datasource
apiVersion: 1

datasources:
  - name: My datasource
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
  
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  version: 1
  editable: true